Remove deprecation layer
doctrine/DoctrineFixturesBundle pull request #312
Opened 2020-04-11 13:28 UTC by greg0ire

`doctrine/persistence` already provides a deprecation layer for this by
using class aliases: Doctrine\Common\Persistence\ManagerRegistry and
Doctrine\Persistence\ManagerRegistry are two names for the same thing,
there is no need for another layer here, and the type declaration can be
restored as it was before.

2020-04-11 13:29 UTC, greg0ire commented
Sorry @lstrojny , I should have spotted this when reviewing #307, since I'm the author of the deprecation layer in `doctrine/persistence` :sweat_smile:

2020-04-13 12:22 UTC, SenseException requested changes
* Resources/doc/index.rst still has `Doctrine\Common\Persistence`
* `Tests/Fixtures/FooBundle` is using `Doctrine\Common\Persistence` as namespace
* I assume `Tests/DeprecationUtil.php` isn't needed anymore, is it?

2020-04-13 15:45 UTC, greg0ire commented
Not exactly what this PR aims to fix, but good points! Please review again.

2020-04-13 18:34 UTC, SenseException approved these changes

2020-04-16 18:35 UTC, merged